services:
  app:
    build:
      context: .
      args:
        options: --reload
    environment:
      - PORT=3000
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    ports:
      - 3000:3000
    volumes:
      - ./:/app